apiVersion: v1
kind: Service
metadata:
  name: mywas-svc
spec:
  selector:
    app: mywas
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mywas
  template:
    metadata:
      labels:
        app: mywas
    spec:
      containers:
      - name: mywas
        image: cicd-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      initContainers:
       - name: init-mydb
         image: busybox:1.28
         command: ['sh', '-c', "until nslookup db-0.mysql-svc.default.svc.cluster.local.; do echo waiting for db; sleep 2; done"]
