apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- 02was.yaml
resources:
- 02was.yaml
images:
- name: cicd-image
  newName: kkyungjin/rapa-cicdlab
  newTag: v28
namespace: default